const properties = [
  {
    id: 1,
    title: "Green Valley Residency",
    type: "Luxury Villa",
    badge: "For Sale",
    location: "Whitefield, Bangalore",
    price: "₹ 3.2 Cr",
    beds: 3, baths: 3, rating: 4.5,
    area: "2,800 sq ft",
    img: "images/v1.jpg",
    imgs: ["images/v9.jpg", "images/v10.jpg"],
    desc: "A stunning luxury villa nestled in a serene green environment with world-class amenities and modern interiors. This property offers spacious living areas and a private garden.",
    amenities: ["Swimming Pool", "Gym", "24/7 Security", "Parking", "Clubhouse"]
  },
  {
    id: 2,
    title: "Skyline Heights",
    type: "Premium Apartment",
    badge: "For Sale",
    location: "Koramangala, Bangalore",
    price: "₹ 2.8 Cr",
    beds: 3, baths: 2, rating: 4.7,
    area: "1,800 sq ft",
    img: "images/v2.webp",
    imgs: ["images/v11.jpg", "images/v12.jpg"],
    desc: "A premium high-rise apartment offering breathtaking city views and top-of-the-line facilities in a prime location.",
    amenities: ["Rooftop Garden", "Intercom", "Elevator", "Power Backup", "Gym"]
  },
  {
    id: 3,
    title: "Elite Garden Villas",
    type: "Modern Villa",
    badge: "For Sale",
    location: "Indiranagar, Bangalore",
    price: "₹ 1.9 Cr",
    beds: 4, baths: 4, rating: 4.5,
    area: "3,200 sq ft",
    img: "images/v3.webp",
    imgs: ["images/v9.jpg", "images/v10.jpg"],
    desc: "Elegant garden villas with spacious interiors, landscaped gardens, and an exclusive community lifestyle.",
    amenities: ["Private Pool", "Yoga Deck", "Smart Home", "Solar Power"]
  },
  {
    id: 4,
    title: "Royal Crest Villas",
    type: "Skyline Luxury Villa",
    badge: "For Sale",
    location: "Hebbal, Bangalore",
    price: "₹ 5.8 Cr",
    beds: 5, baths: 5, rating: 4.6,
    area: "5,500 sq ft",
    img: "images/v4.webp",
    imgs: ["images/v11.jpg", "images/v12.jpg"],
    desc: "Majestic skyline villas offering panoramic views, private pools, and premium finishes for the discerning buyer.",
    amenities: ["Infinity Pool", "Home Cinema", "Wine Cellar", "Service Quarters"]
  },
  {
    id: 5,
    title: "Green Park Residences",
    type: "Urban Premium Apartment",
    badge: "For Rent",
    location: "Electronic City, Bangalore",
    price: "₹ 1.2 L / month",
    beds: 3, baths: 3, rating: 4.9,
    area: "2,200 sq ft",
    img: "images/v5.webp",
    imgs: ["images/v9.jpg", "images/v10.jpg"],
    desc: "Premium urban apartments with lush green surroundings, modern amenities, and excellent connectivity.",
    amenities: ["Jogging Track", "Tennis Court", "Library", "Cafeteria"]
  },
  {
    id: 6,
    title: "Seaview Enclave",
    type: "Beachside Luxury Villa",
    badge: "For Rent",
    location: "Sarjapur Road, Bangalore",
    price: "₹ 2.5 L / month",
    beds: 4, baths: 3, rating: 4.6,
    area: "3,800 sq ft",
    img: "images/v6.webp",
    imgs: ["images/v11.jpg", "images/v12.jpg"],
    desc: "Breathtaking beachside luxury villa offering serene waterfront living with private beach access and resort-style amenities.",
    amenities: ["Beach Access", "BBQ Area", "Jacuzzi", "Fire Pit"]
  },
  {
    id: 7,
    title: "Metro Star Homes",
    type: "Modern City Apartment",
    badge: "For Sale",
    location: "MG Road, Bangalore",
    price: "₹ 4.5 Cr",
    beds: 2, baths: 2, rating: 4.6,
    area: "1,400 sq ft",
    img: "images/v7.avif",
    imgs: ["images/v9.jpg", "images/v10.jpg"],
    desc: "Smart city apartments with cutting-edge design, premium interiors, and unmatched urban connectivity.",
    amenities: ["Smart Lock", "Underground Parking", "Meeting Room"]
  },
  {
    id: 8,
    title: "Palm Grove Villas",
    type: "Elegant Family Villa",
    badge: "For Sale",
    location: "JP Nagar, Bangalore",
    price: "₹ 3.0 Cr",
    beds: 4, baths: 3, rating: 4.8,
    area: "3,000 sq ft",
    img: "images/v8.avif",
    imgs: ["images/v11.jpg", "images/v12.jpg"],
    desc: "Elegant family villas surrounded by palm groves offering a peaceful retreat with top-class community facilities.",
    amenities: ["Kids Play Area", "Meditation Zone", "Badminton Court"]
  }
];
